// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmgsjnxkvigvyabxwebm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZ3NqbnhrdmlndnlhYnh3ZWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTYyNDEsImV4cCI6MjA3MDAzMjI0MX0.TmEm8yS5Zg9YeXzbzpfwRkTjf6en4quaA05WZUvGhYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});